# Generated by Django 5.2.4 on 2025-07-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_student_created_at_remove_student_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
