# Generated by Django 5.2.4 on 2025-07-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_student_s_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_addr',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_class',
            field=models.CharField(max_length=200, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_contactnumber',
            field=models.CharField(default='9999999999', max_length=15, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_fathername',
            field=models.CharField(max_length=200, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_mothername',
            field=models.CharField(max_length=200, verbose_name='mother Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(max_length=200, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_school',
            field=models.CharField(max_length=200, verbose_name='school name'),
        ),
    ]
