# Generated by Django 5.2.4 on 2025-08-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duration (e.g. 6 months)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_contactnumber',
            field=models.CharField(default='9999999999', max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_fathername',
            field=models.CharField(max_length=200, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_mothername',
            field=models.CharField(max_length=200, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_school',
            field=models.CharField(max_length=200, verbose_name='School Name'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='authentication.stream')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='authentication.subject'),
            preserve_default=False,
        ),
    ]
