# Generated by Django 5.2.4 on 2025-08-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_stream_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.stream'),
        ),
    ]
