# Generated by Django 5.2.4 on 2025-08-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_stream_name_alter_subject_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.stream'),
        ),
    ]
